### ISSUE TITLE
Program description contains sometimes XML CDATA closing tag

### ISSUE THREAD

**Issue by Thorsten1976** [ds10git/tvbrowserandroid#12]
Probably a parsing/ regex  issue. Description contains "]]>" at the end (ZDF 17.2.2016 18:35 "Die Spezialisten - Im Namen der Opfer"):

![device-2016-02-17-202805](https://cloud.githubusercontent.com/assets/6201441/13121973/005b6158-d5b5-11e5-9448-6dfc0fe2606f.png)

**Comment by ds10git** [comment]
TV data issue, not issue of TV-Browser.
