### ISSUE TITLE
Program description / some entries truncated (Musik:)

### ISSUE THREAD

**Issue by Thorsten1976** [ds10git/tvbrowserandroid#13]
If a program description contains an entry "Musikalische Leitung: ..." the entry is truncated to "Musik: alische Leitung:" (regex/parsing/substring/startsWith issue?).

If the locale is English the entry is truncated to "Music: alische Leitung: ..." (requires: German program info data).

**Comment by ds10git** [comment]
TV data issue, not issue of TV-Browser.
