### ISSUE TITLE
APK releases

### ISSUE THREAD

**Issue by tinxx** [ds10git/tvbrowserandroid#14]
Please add APK releases in addition to the source code releases.

On the [website](http://android.tvbrowser.org/index.php?id=download) there are APK releases. But the connection is not TLS secured.

Please add APK files to the github repository so that there is a way to get android packages through a verified channel for people that don't use official distribution channels (e.g. Google Play).

**Comment by ds10git** [comment]
Release added.

**Comment by tinxx** [comment]
Thanks for the quick response!
