### ISSUE TITLE
please provide plugins outside of playstore

### ISSUE THREAD

**Issue by DJCrashdummy** [ds10git/tvbrowserandroid#27]
similar to #14, is it possible to provide (at least the free) plugins in any other way than just at the playstore? - i don't use google at all, so it is pretty troublesome to get them...
IMHO as mentioned in https://github.com/ds10git/tvbrowserandroid/issues/16#issuecomment-347985625, fdroid (maybe an own repo, if the [license-problem](https://github.com/ds10git/tvbrowserandroid/issues/7) is also valid for the plugins) would be the best solution - so also updating will work pretty smooth, but an apk in github will also be nice.

_sorry for posting this here, but i thought this is better than posting it for every plugin separately._

**Comment by ds10git** [comment]
Plugins are available outside of playstore for the free version of TV-Browser: https://www.tvbrowser-app.de/index.php?id=plugins-1
